### ISSUE TITLE
Unable to open/view JAR archives

### ISSUE THREAD

**Issue by mc-butler** [MidnightCommander/mc#4569]
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/4569 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `alexm` (@amorozov) |

<p>
This is an <em>almost</em> a copy of #4208, some three years later.<br />
</p>
<p>
System: Manjaro/x64<br />
MC: 4.8.31-3.<br />
</p>
<p>
On pressing &lt;Enter&gt; on a JAR nothing happens.<br />
On pressing &lt;F3&gt; on s JAR an error message pops up: Cannot open "/path/to/file.jar" in parse mode Operation not supported (95)<br />
Renaming JAR to ZIP solves the problem<br />
</p>
<p>
<strong>LC_MESSAGES=C mc -V</strong><br />
</p>

```
Built with GLib 2.78.4
Built with S-Lang 2.3.3 with terminfo database
Built with libssh2 1.11.0
With builtin Editor and Aspell support
With subshell support as default
With support for background operations
With mouse support on xterm and Linux console
With support for X11 events
With internationalization support
With multiple codepages support
With ext2fs attributes support
Virtual File Systems:
 cpiofs, tarfs, sfs, extfs, ftpfs, sftpfs, shell
Data types:
 char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;
```
<p>
<strong>LC_MESSAGES=C mc -F</strong><br />
</p>

```
Home directory: /home/alex
Profile root directory: /home/alex

[System data]
    Config directory: /etc/mc/
    Data directory:   /usr/share/mc/
    File extension handlers: /usr/lib/mc/ext.d/
    VFS plugins and scripts: /usr/lib/mc/
        extfs.d:        /usr/lib/mc/extfs.d/
        shell:          /usr/lib/mc/shell/

[User data]
    Config directory: /home/alex/.config/mc/
    Data directory:   /home/alex/.local/share/mc/
        skins:          /home/alex/.local/share/mc/skins/
        extfs.d:        /home/alex/.local/share/mc/extfs.d/
        shell:          /home/alex/.local/share/mc/shell/
        mcedit macros:  /home/alex/.local/share/mc/mc.macros
        mcedit external macros: /home/alex/.local/share/mc/mcedit/macros.d/macro.*
    Cache directory:  /home/alex/.cache/mc/
```
<p>
<strong>mc --configure-options</strong><br />
</p>

```
'--prefix=/usr' '--libexecdir=/usr/lib' '--sysconfdir=/etc' '--enable-aspell' '--with-screen=slang' '--with-x' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/mc/src=/usr/src/debug/mc -flto=auto' 'LDFLAGS=-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -flto=auto'
```
<p>
<strong>file httpcore-4.4.10.jar</strong><br />
</p>

```
httpcore-4.4.10.jar: Java archive data (JAR)
```
<p>
<strong>section [jar] of /etc/mc/mc.ext.ini</strong><br />
</p>

```
Type=\(Java\ (Jar\ file|archive)\ data\ \((zip|JAR)\)
TypeIgnoreCase=true
Open=%cd %p/uzip://
View=%view{ascii} /usr/lib/mc/ext.d/archive.sh view zip
```

**Comment by rajdikshant** [comment]
Unable to open ODS file. Default application is Gnumeric. Same (95) error.

System: Debian 13.1
MC: 4.8.33

**Comment by zyv** [comment]
Feel free to create a proper bug report, or better yet, investigate what's going on with your `mc.ext` rules. Problems with escaping that we were aware of were resolved in version 4.8.33.

**Comment by rajdikshant** [comment]
Created a new report: #4760

**Comment by ibm5110** [comment]
Problem still persists with 4.8.33:
```
GNU Midnight Commander 4.8.33
Built with GLib 2.84.4
Built with S-Lang 2.3.3 with terminfo database
Built with libssh2 1.11.1
With builtin editor and aspell support
With subshell support as default
With support for background operations
With mouse support on xterm and Linux console
With support for X11 events
With internationalization support
With multiple codepages support
With ext2fs attributes support
Virtual File Systems:
 cpiofs, tarfs, sfs, extfs, ext2undelfs, ftpfs, sftpfs, shell
Data types:
 char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64; uintmax_t: 64;
```
```
# file Public_Release.jar
Public_Release.jar: Zip archive data, made by v2.0 UNIX, extract using at least v2.0, last modified Dec 05 2025 14:18:12, uncompressed size 0, method=deflate
```
I always get "Operation not supported (95)" when I try to view the file within mc. Renaming the file to ...zip works.
Heres the section of the mc.ext.ini:
```
[jar]
Type=\\(Java (Jar file|archive) data \\((zip|JAR)\\)\\)
TypeIgnoreCase=true
Open=%cd %p/uzip://
View=%view{ascii} /usr/lib/mc/ext.d/archive.sh view zip
```

BTW calling `MC_EXT_FILENAME=Public_Release.jar /usr/lib/mc/ext.d/archive.sh view zip` does work! So it must be a problem within mc or with the parsing of the output.

**Comment by zyv** [comment]
> BTW calling `MC_EXT_FILENAME=Public_Release.jar /usr/lib/mc/ext.d/archive.sh view zip` does work! So it must be a problem within mc or with the parsing of the output.

No, obviously the output of `file` doesn't match the regex. Maybe we should just give up and merge #4862 😢

**Comment by ibm5110** [comment]
> No, obviously the output of `file` doesn't match the regex.

Is that the case? If `file` says that it is a ZIP archive, then why doesn't the rule for ZIP files apply? I mean, if the file extension is ignored because `file` is used to determine the type, mc should just treat is as ZIP file.
The zip-by-type rules in mc.ext.ini should apply here, but why is it ignored?
```
[zip-by-type]
Type=\\(Zip archive
Open=%cd %p/uzip://
View=%view{ascii} /usr/lib/mc/ext.d/archive.sh view zip
```

**Comment by ibm5110** [comment]
Perhaps there is a bug within `file`. This is what I get with the parameters suggested in #4862 :
```
# file -z -b -L -S Public_Release.jar
ERROR:[gzip: ] (data)
# file -b -L -S Public_Release.jar
Zip archive data, made by v2.0 UNIX, extract using at least v2.0, last modified Dec 05 2025 14:10:42, uncompressed size 0, method=deflate
```

**Comment by zyv** [comment]
> Perhaps there is a bug within `file`. This is what I get with the parameters suggested in #4862:
> 
> ```
> # file -z -b -L -S Public_Release.jar
> ERROR:[gzip: ] (data)
> ```

This would explain it. Either there is something wrong with the specific file, or you hit a bug in the `file` utility.
