### ISSUE TITLE
Directory and input line history (Alt+h) comes back after clearing

### ISSUE THREAD

**Issue by DrinkDregs** [MidnightCommander/mc#4783]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Midnight Commander version and build configuration

```shell
GNU Midnight Commander 4.8.33
Built with GLib 2.82.4
Built with S-Lang 2.3.3 with terminfo database
Built with libssh2 1.11.1
With builtin editor and aspell support
With subshell support as default
With support for background operations
With mouse support on xterm and Linux console
With support for X11 events
With internationalisation support
With multiple codepages support
With ext2fs attributes support
Virtual File Systems:
 cpiofs, tarfs, sfs, extfs, ftpfs, sftpfs, shell
Data types:
 char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64; uintmax_t: 64;
```

### Operating system

```shell
6.12.43-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 20 Aug 2025 17:50:11 +0000 x86_64 GNU/Linux
```

### Is this issue reproducible using the latest version of Midnight Commander?

- [ ] I confirm the issue is still reproducible with the latest version of Midnight Commander

### How to reproduce

- Open directory history: `Alt`+`H`
- Clear all directory history: `D`

### Expected behavior

The directory history is deleted from `~/.local/share/mc/history` and so will not return.

### Actual behavior

The directory history is not deleted from `~/.local/share/mc/history`.
If directory history is invoked again (`Alt`+`H`) it has all returned.

**Comment by zyv** [comment]
I cannot reproduce this. How exactly do you do this? For me, the history is cleared and gone.

There is another bug though. The deletion confirmation dialog is not centered, and so for almost empty history, it shows below the bottom of the screen. This could be an easy fix though? @aborodin

**Comment by mc-worker** [comment]
> The directory history is not deleted from `~/.local/share/mc/history`. If directory history is invoked again (`Alt`+`H`) it has all returned.

Looks like you cannot write to this file or directory as user (usually, this is a result of run `mc` under wrong configured `sudo` or using `su` instead of `su -`). Please check all permissions in n `~./cache/mc`, `~/.config/mc`, and `~/.local/share/mc`.

**Comment by mc-worker** [comment]
> The deletion confirmation dialog is not centered, and so for almost empty history, it shows below the bottom of the screen.

I cannot reproduce this.

**Comment by zyv** [comment]
> > The deletion confirmation dialog is not centered, and so for almost empty history, it shows below the bottom of the screen.
> 
> I cannot reproduce this.

<img width="1541" height="996" alt="Image" src="https://github.com/user-attachments/assets/c2a07a58-96ba-4d6f-9822-dfcf050c2159" />

1. Clear history
2. Add one entry
3. Press Shift+D

**Comment by mc-worker** [comment]
Ah. This is not a directory history. This is a history of the command line.

**Comment by zyv** [comment]
> Ah. This is not a directory history. This is a history of the command line.

Oh, thanks for pointing this out. I think I can reproduce the issue with the **directory** history now.

1. Press F7
2. Press Alt+H
3. Press Shift+D
4. Press Enter
5. ... history is now gone ...
6. Press Enter
7. Press Cancel

Now start from the beginning. The history comes back. If the dialog is **not** canceled, then the history is really gone.

**Comment by mc-worker** [comment]
> I think I can reproduce the issue with the **directory** history now.

This is not a directory history too.

I think a some confusion is here. 
  
- `Alt-H` (`H` is **uppercase letter**) opens the directory history of file panel.
- `Alt-h` (`h` is **lowercase letter**) opens the history of input line in the dialog.

But yes, if dialog is closed with value other than B_CANCEL, the input line history is not saved (see `input_save_history()` function).

**Comment by zyv** [comment]
> > I think I can reproduce the issue with the **directory** history now.
> 
> This is not a directory history too.
> 
> I think a some confusion is here.
> 
> * `Alt-H` (`H` is **uppercase letter**) opens the directory history of file panel.
> * `Alt-h` (`h` is **lowercase letter**) opens the history of input line in the dialog.

You are right! If I open the **real** directory history of the file panel (`Alt+H`), I cannot reproduce, just as for `Alt+h`.

> But yes, if dialog is closed with value other than B_CANCEL, the input line history is not saved (see `input_save_history()` function).

So do you think this is a bug or a feature? I think that's quite unexpected, but it is true that I would only expect emptying of the history to stick in any case, and not some arbitrary entries in the dialog. I wonder how complicated it is to make an exception for clearing...

**Comment by DrinkDregs** [comment]
> Press F7
Press Alt+H
Press Shift+D
Press Enter
... history is now gone ...
Press Enter
Press Cancel
Now start from the beginning. The history comes back. If the dialog is not canceled, then the history is really gone.

What am I supposed to press after clearing the history? If I press `Enter` the history returns. If I press `Esc` the history returns. Is `Esc` what you mean by 'Cancel'?

**Comment by zyv** [comment]
> What am I supposed to press after clearing the history? If I press `Enter` the history returns. If I press `Esc` the history returns. Is `Esc` what you mean by 'Cancel'?

We cannot reproduce the issue that you are describing. Did you check the permissions on the files in your home directory as advised by Andrew?

**Comment by zyv** [comment]
@mc-worker I've just tested this, and the position of the dialog for `Alt+h/H` is now fixed.

However, if I use F7 to test the line history clearing, then nothing has changed for me. It's still only cleared when I click OK in the new directory dialog and not when I click Cancel.

**Comment by mc-worker** [comment]
> not when I click Cancel.

Fixed.

**Comment by DrinkDregs** [comment]
> We cannot reproduce the issue that you are describing. Did you check the permissions on the files in your home directory as advised by Andrew?

I own `~/.local/share/mc/history` and the permisions are `0600`. I know I have write access, since every time I open a directory, it gets written to the file.

**Comment by zyv** [comment]
> > We cannot reproduce the issue that you are describing. Did you check the permissions on the files in your home directory as advised by Andrew?
> 
> I own `~/.local/share/mc/history` and the permisions are `0600`. I know I have write access, since every time I open a directory, it gets written to the file.

Can you do a screencast or something? It's still not clear which history you are referring to, and how can we reproduce it not being cleared? Panel and command history are being cleared for me. Do you have any special settings turned on as compared to defaults? Can you reproduce it if you start mc as follows:

```
MC_PROFILE_ROOT=$HOME/mc-test mc
```

This will make it use `mc-test` as the settings directory, so it will start with default settings only and with a directory that is writable by the user.

I have found out that the history of line input controls is not cleared if the dialog is canceled, and this is now fixed in the connected branch. But if the dialog is closed, then it was also cleared before. So this doesn't sound like the problem that you are describing.

**Comment by DrinkDregs** [comment]
I tried `MC_PROFILE_ROOT=$HOME/mc-test mc` and there's no difference.

If I delete history entries by pressing `d`, they remain deleted. If I try to delete them all by pressing `D`, they return.

As instructed, I've attached a video showing what happens. In the video, I press `Alt`+`H` to open the directory history, then press `D` and `Enter` to delete it all, then press `Enter` to exit the history (`Esc` has the same effect). Then I restart Midnight Commander and press `Alt`+ `H` again, and you can see that the history has returned.

https://github.com/user-attachments/assets/d2db9705-6243-43d5-8b3f-23fb286942b0

**Comment by zyv** [comment]
Okay, @aborodin, thanks to @DrinkDregs’ video, I think I can also reproduce it with directory history:

The trick is to exit `mc` immediately after clearing the history and then start again. In this case, the history indeed comes back. If you visit any other directory in the meantime, then it's cleared for good.

I think this is the same problem that you've fixed for line inputs now. There must be some null check on the list somewhere, and the section is not removed from the file if the list is empty...

**Comment by mc-worker** [comment]
> There must be some null check on the list somewhere, and the section is not removed from the file if the list is empty...

You're right. Fixed.

**Comment by zyv** [comment]
I can confirm that with the latest commit, both command and directory history do not come back when cleared. Thank you!
